PNC = PNC or {}
PNC.Const = PNC.Const or {}

local Const = PNC.Const

Const.MOD_ID = "PsychopatzNPC-Core"
Const.MODULE = "PNC"
Const.MODDATA_KEY = "PNC_Core_Global"

Const.CMD_FULL_SYNC_REQUEST = "RequestFullSync"
Const.CMD_FULL_SYNC = "FullSync"
Const.CMD_SYNC_RECORD = "SyncRecord"
Const.CMD_REMOVE_RECORD = "RemoveRecord"
Const.CMD_DEBUG = "DebugCommand"

Const.PRESENCE_LIVE = "live"
Const.PRESENCE_ABSTRACT = "abstract"
Const.PRESENCE_CORPSE = "corpse"

Const.ORDER_FOLLOW = "follow"
Const.ORDER_GUARD = "guard"
Const.ORDER_PATROL = "patrol"
Const.ORDER_HOSTILE_ROAM = "hostile_roam"
Const.ORDER_HOSTILE_HUNT = "hostile_hunt"

Const.TICK_LIVE_HOT_MS = 100
Const.TICK_LIVE_WARM_MS = 250
Const.TICK_LIVE_COLD_MS = 1000
Const.TICK_ABSTRACT_MS = 3000

Const.MATERIALIZE_DISTANCE = 28
Const.ABSTRACT_DISTANCE = 40
Const.SPATIAL_CELL_SIZE = 16

Const.MELEE_RANGE = 1.3
Const.RANGED_RANGE = 8.5
Const.GUARD_RADIUS = 3.0
Const.FOLLOW_DISTANCE = 1.8
Const.FOLLOW_WALK_DISTANCE = 4.0
Const.FOLLOW_RUN_DISTANCE = 8.0
Const.PATROL_REACHED_DISTANCE = 0.8

Const.LIVE_WALK_STEP = 0.09
Const.LIVE_RUN_STEP = 0.14
Const.ABSTRACT_TRAVEL_STEP = 5.0
Const.UNARMED_DAMAGE = 3
Const.UNARMED_GROUND_DAMAGE = 5
Const.UNARMED_COOLDOWN_MS = 1400

Const.DOWNED_TIMEOUT_MS = 30000
Const.INCAPACITATED_TIMEOUT_MS = 30000
Const.INCAPACITATED_GRACE_MS = 1500
Const.INCAPACITATED_HP = 1
Const.INCAPACITATED_ENGINE_BUFFER = 1.5
Const.DEBUG_COMBAT_HOLD_MS = 2500
Const.DEFAULT_HP_MAX = 100
Const.DEFAULT_ENGINE_BUFFER = 2
Const.RECENT_DAMAGE_SHOW_MS = 4000
Const.ZOMBIE_TARGET_RADIUS = 12
Const.ZOMBIE_AGGRO_RADIUS = 14
Const.ZOMBIE_AGGRO_KEEP_RADIUS = 2.4
Const.ZOMBIE_TARGET_PLAYER_KEEP_RADIUS = 2.0
Const.ZOMBIE_ATTACK_RANGE = 0.95
Const.ZOMBIE_ATTACK_COOLDOWN_MS = 1500
Const.ZOMBIE_ATTACK_DAMAGE = 12
Const.ZOMBIE_BITE_APPLY_DELAY_MS = 450
Const.ZOMBIE_BITE_CLEAR_DELAY_MS = 700
Const.ZOMBIE_BITE_APPLY_TICK = 14
Const.ZOMBIE_BITE_CLEAR_TICK = 16
Const.ZOMBIE_BITE_DISTANCE = 0.8
Const.STEALTH_DISCOVERY_RADIUS = 10
Const.STEALTH_BREAK_CONTACT_DISTANCE = 1.2
